### ISSUE TITLE
Sending Email Failed

### ISSUE THREAD

**Issue by CatCodeMe** [scouter-project/scouter-plugin-server-alert-email#10]
![image](https://user-images.githubusercontent.com/11496772/37952816-a948219e-31d3-11e8-86e2-57f7fb56b4af.png)
I create a new Gmail account for testing . But I meet three issues.

1. When I **shutdown** tomcat , but I can't find any logs in the file "${scouter.server}/logs/server-${date}.log" 
2. When I **start** tomcat , there are some logs like this ！While I set port to 587, it seems to not work.
![image](https://user-images.githubusercontent.com/11496772/37953293-10ded004-31d5-11e8-9f57-a40a3b64caa4.png)
3. Last , I can't find more logs.  And I had not found how the logs generated.

**Comment by CatCodeMe** [comment]
This is my scouter.conf, path is : ${scouter}/server/conf/scouter.conf.
![image](https://user-images.githubusercontent.com/11496772/37953666-1d28a91a-31d6-11e8-8b14-964c38a15e1a.png)

**Comment by nices96** [comment]
1. Scouter server 's standard out is terminal and append output to "${scouter.server}/nohup.out".
2. Please check your network state and host reachability to smtp.gmail.com using telnet command.
    scouter.server ~]$ telnet smtp.gmail.com 587
    Trying 108.177.97.109...
    Connected to gmail-smtp-msa.l.google.com.
    Escape character is '^]'.
    220 smtp.gmail.com ESMTP l66sm2536552pfc.184 - gsmtp
3. If you add a below configuration to scouter server, you can see more detail logs in nohup.out.
    `_trace=true`

**Comment by CatCodeMe** [comment]
Thanks for your reply ! It helps me a lot. Finally, I found an issue.

1. My server **can't**  telnet to smtp.gmail.com. And I use other public smtp service.
2. I test successfully with  smtp server -- "smtp.163.com". It supports **SSL/TLS(port 465)** and **non SSL(port 25)**. 
![image](https://user-images.githubusercontent.com/11496772/38162216-eb57e094-350f-11e8-8656-44cf98627b91.png)
3. I found the issue that you directly use **email.setSmtpPort(port);**  in **EmailPlugin.java (line 214)**. 
4. Finally, I suggest **EmailPlugin.java**  can support to use **email.setSslSmtpPort(port)** , because we
usually use **ssl/tls** smtp service in most companies.
5. BTW, the plugin can change to Maven or Gradle , I find it buliding with Ant. :)

**Comment by CatCodeMe** [comment]
Oh !  The email jar is this one.
![image](https://user-images.githubusercontent.com/11496772/38162595-406593be-3516-11e8-97c8-40796499369b.png)

**Comment by nices96** [comment]
Can you test with below parameters?
`ext_plugin_email_smtp_port=587`
`ext_plugin_email_tls_enabled=true`

ASAP I'll add options for SSL and convert to maven project.

**Comment by CatCodeMe** [comment]
I test with this one which supports **587**.
![image](https://user-images.githubusercontent.com/11496772/38181810-a6c03e82-3667-11e8-8ab6-57c631934acb.png)
I find both **email.setSslSmtpPort("587")** and **email.setSmtpPort(587)** work successfully . It
likes **"Demo Config"** like README.md, this smtp service "smtp.qq.com" maybe works as same as "smtp.gmail.com".

**Comment by nices96** [comment]
I converted to maven project and add below options for SSL/TLS.
`ext_plugin_email_ssl_enabled`
`ext_plugin_email_starttls_enabled`

If you haven't any problem, please close this issue.

**Comment by CatCodeMe** [comment]
Thanks ! It works.
