### ISSUE TITLE
facing an issue while installation of tomcat  

### ISSUE THREAD

**Issue by sandeep1809** [scouter-project/scouter-plugin-server-alert-email#11]
Hi,

I am facing an issue while installing tom in my system, request you to share the detailed procedure to install tomcat.

issue faced:- when we start the Tomcat it open and closed with seconds.

Regards,
Sandeep

**Comment by nices96** [comment]
Do you mean you having trouble installing tomcat in your system?
Please refer to https://tomcat.apache.org/tomcat-8.0-doc/RUNNING.txt

Additionally if you want use scouter to tomcat monitoring, please read below guide.
https://github.com/scouter-project/scouter/blob/master/scouter.document/main/Setup.md
